spring.application.name=boot_jsp

server.port=8070

spring.mvc.static-path-pattern=/resources/**
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.view-names=thymeleaf/*

spring.https.encoding.charset=UTF-8

#server.ssl.enabled=true
#server.ssl.key-store=Wildcard.hdel.co.kr_jks.jks
#server.ssl.key-store-type=JKS
#server.ssl.key-store-password=hdel.co.kr


spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://;serverName=10.225.80.35;port=1433;databaseName=PLMPRDIF;encrypt=false
spring.datasource.username=sa
spring.datasource.password=AutodeskVault@26200

## validate : 운영에서는 validate 가 가장좋은 옵션이다.
## update 추가 된 컬럼들을 자동을 추가해주나 이미 있는 걸럼을 없앤 것에 대해서는 삭제해주지않는다.
#validate
#create
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.output.ansi.enabled=always

logging.level.org.hibernate.type.descriptor.sql=trace


##MyBatis
mybatis.type-aliases-package=com.kyhslam.dto
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.kyhslam.dto.repository.mybatis=trace

#JPA log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE